services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: oc-lettings-site:${DOCKER_TAG}
    ports:
      - "8000:8000"
    volumes:
      - ./oc-lettings-site.sqlite3:/app/oc-lettings-site.sqlite3
      - ./static:/app/static
    env_file:
      - .env