name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
      
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Linting
        run: |
          flake8 .
      
      - name: Run Tests with Coverage
        env:
          CI: true
          SECRET_KEY: "something"
          DEBUG: ${{ secrets.DEBUG }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        run: |
          coverage run -m pytest
          coverage report --fail-under=80
          coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4.4.3
        with:
          name: coverage-report
          path: ./htmlcov

  containerize:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t oc-lettings-site:${{ github.sha }} .
          docker tag oc-lettings-site:${{ github.sha }} cuteslime/oc-lettings-site:${{ github.sha }}
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push cuteslime/oc-lettings-site:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: containerize
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Update Docker Image and Trigger Redeployment on Render
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceDetails": {
              "id": "${{ secrets.RENDER_SERVICE_ID }}",
              "dockerImage": "cuteslime/oc-lettings-site:${{ github.sha }}"
            }
          }' https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }} && \
          echo "Image updated successfully. Triggering redeployment..." && \
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
